### ISSUE TITLE
Invalid build version for babel istanbul plugin

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-sensors#5]
```
TypeError: Invalid Version: https://registry.npmjs.org/istanbul-lib-instrument/-/istanbul-lib-instrument-1.8.0.tgz
    at new SemVer (/Users/ojha/Github/cognicity-sensors/node_modules/istanbul-lib-instrument/node_modules/semver/semver.js:293:11)
    at major (/Users/ojha/Github/cognicity-sensors/node_modules/istanbul-lib-instrument/node_modules/semver/semver.js:551:10)
    at Object.<anonymous> (/Users/ojha/Github/cognicity-sensors/node_modules/istanbul-lib-instrument/dist/constants.js:19:117)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

**Comment by tomasholderness** [comment]
This doesn't seem to be an issue anymore (probably due to dependency update). Please re-open if a problem in the future.
